## Numpy

In [2]:
import numpy as n
a=n.array([[1,2,3],
         [4,5,6]])
a
#shape(row,coloumn)--(2,3)
#dimension-2
#rank-2

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
type(a)

numpy.ndarray

In [4]:
dir(n)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

In [5]:
a.ndim

2

In [6]:
a.shape

(2, 3)

In [7]:
a.dtype

dtype('int32')

In [12]:
#creating an Array with the type float
a=n.array([[1,2,3],
          [4,5,6]],dtype='float')
a        

array([[1., 2., 3.],
       [4., 5., 6.]])

In [13]:
#creating an array with the type complex
a=n.array([[1,2,3],[4,5,6]],dtype='complex')
a

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [14]:
# creating an array using tuple
a=n.array((1,2,3))
a

array([1, 2, 3])

In [16]:
#sreate array with zeros
a=n.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
#create array with ones
a=n.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
a=n.full((2,3),5,dtype='int')
a

array([[5, 5, 5],
       [5, 5, 5]])

In [21]:
# create array with given any number
a=n.full((2,3),2,dtype='complex')
a

array([[2.+0.j, 2.+0.j, 2.+0.j],
       [2.+0.j, 2.+0.j, 2.+0.j]])

In [22]:
a=n.full((2,3),7,dtype='float')
a

array([[7., 7., 7.],
       [7., 7., 7.]])

In [24]:
#to create an array with random values
a=n.empty((2,3),dtype='complex')
a

array([[1.11433166e-311+2.47032823e-322j,
        0.00000000e+000+0.00000000e+000j,
        0.00000000e+000+3.69776220e-062j],
       [6.87249201e-091+4.04459807e-037j,
        5.51219938e+169+6.58544473e-066j,
        3.99910963e+252+1.46030983e-319j]])

In [25]:
a=n.empty((3,3),dtype='int')
a

array([[ 538604632,        525,  538976288],
       [1734964000, 1768319342, 1953390947],
       [ 170473533,  538976288,  540950078]])

In [26]:
a=n.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
a.max() #maximum element of array

9

In [28]:
a.min()  # minimum element of array

1

In [34]:
a.max(axis=0)  # row wise maximum value

array([7, 8, 9])

In [30]:
a.min(axis=1) # coloumn wise minimu values

array([1, 4, 7])

In [31]:
a.min(axis=0)  # row wise minimum values

array([1, 2, 3])

In [35]:
a.max(axis=1) # coloumn wise maximum values

array([3, 6, 9])

In [36]:
# To find out the cumulative sum
a.cumsum(axis=1)  # row wise cumulative sum

array([[ 1,  3,  6],
       [ 4,  9, 15],
       [ 7, 15, 24]], dtype=int32)

In [37]:
a.cumsum(axis=0)   # column wise cumulative sum

array([[ 1,  2,  3],
       [ 5,  7,  9],
       [12, 15, 18]], dtype=int32)

In [38]:
# to find the transpose
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## OPERATORS

In [45]:
a=n.array([1,2,3])
a

array([1, 2, 3])

In [46]:
a+1

array([2, 3, 4])

In [47]:
a-2

array([-1,  0,  1])

In [48]:
a**2

array([1, 4, 9], dtype=int32)

In [58]:
a=n.array([[1,2],[4,5],[7,8]])
b=n.array([[5,6],[6,7],[7,8]])
a
b

array([[5, 6],
       [6, 7],
       [7, 8]])

In [52]:
a+b

array([[ 6,  8],
       [10, 12],
       [14, 16]])

In [54]:
a-b

array([[-4, -4],
       [-2, -2],
       [ 0,  0]])

In [55]:
a/b

array([[0.2       , 0.33333333],
       [0.66666667, 0.71428571],
       [1.        , 1.        ]])

In [56]:
a//b

array([[0, 0],
       [0, 0],
       [1, 1]], dtype=int32)

In [59]:
n.add(a,b)

array([[ 6,  8],
       [10, 12],
       [14, 16]])

In [60]:
n.subtract(a,b)

array([[-4, -4],
       [-2, -2],
       [ 0,  0]])

In [61]:
n.multiply(a,b)

array([[ 5, 12],
       [24, 35],
       [49, 64]])

In [62]:
n.divide(a,b)

array([[0.2       , 0.33333333],
       [0.66666667, 0.71428571],
       [1.        , 1.        ]])

In [64]:
a=n.array([1,2,3])
a

array([1, 2, 3])

In [67]:
a=n.array([0,90,45])
n.sin(a)

array([0.        , 0.89399666, 0.85090352])

In [68]:
n.sqrt(a)

array([0.        , 9.48683298, 6.70820393])

## Creating an array using Range function


In [69]:
# n.arange(start,stop,step)
a=n.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
a=n.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
a=n.arange(10,20,2)
a

array([10, 12, 14, 16, 18])

In [75]:
a=n.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [76]:
a=n.arange(10).reshape(5,2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [80]:
a=n.arange(40,60).reshape(2,5,2)
a

array([[[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]],

       [[50, 51],
        [52, 53],
        [54, 55],
        [56, 57],
        [58, 59]]])

In [81]:
a=n.arange(10,0,-1).reshape(2,5)
a

array([[10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [84]:
a=n.linspace(1,2,5).reshape(5,1)
a

array([[1.  ],
       [1.25],
       [1.5 ],
       [1.75],
       [2.  ]])

In [88]:
a=n.array([[1,2,3],[4,5,6]])
a.resize(3,2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

## Iterating over the Array


In [94]:
a=n.array([[1,2,3],[4,5,6],[7,8,9]])
for i in iter(a):
    print(i[0])
print(len(a))

1
4
7
3


In [95]:
a.flatten('c')  # Row wise

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
a.flatten('f') # Coloumn wise


array([1, 4, 7, 2, 5, 8, 3, 6, 9])

### INDEXING

In [98]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [99]:
a[0][0]

1

In [100]:
a[0][2]

3

In [101]:
a[2][2]

9

In [102]:
a[1][2]

6

## Identity and Diagonal array

In [103]:
a=n.eye(3,3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [105]:
a=n.identity(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [106]:
a=n.diag(n.arange(5))
a

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [107]:
a=n.diag(n.arange(0,8,2))
a

array([[0, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])

In [109]:
a=n.diag(n.arange(10,30,2))
a

array([[10,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 12,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 14,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 16,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 18,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 20,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 22,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 24,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 26,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 28]])

In [110]:
a=n.diag(n.arange(10,30,2)).reshape(5,20)
a

array([[10,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 12,  0,  0,  0,  0,
         0,  0,  0,  0],
       [ 0,  0, 14,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 16,  0,  0,
         0,  0,  0,  0],
       [ 0,  0,  0,  0, 18,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 20,
         0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 22,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0, 24,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 26,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0, 28]])

## Slicing

In [113]:
a=n.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [114]:
# from 4 index to last
print(a[4::])

[4 5 6 7 8 9]


In [115]:
# from 0 to 4
print(a[:5:])

[0 1 2 3 4]


In [116]:
# from index 4(excluded) up to 7(include)
print(a[5:7])

[5 6]


In [118]:
## Exclude last element
print(a[:9])
# only last element
print(a[-1])

[0 1 2 3 4 5 6 7 8]
9


In [119]:
# from first to last reverse order
print(a[::-1])

[9 8 7 6 5 4 3 2 1 0]


In [122]:
# all even numbers in reverse order
print(a[-2::-2])
## all odd num in reverse order
print(a[::-2])

[8 6 4 2 0]
[9 7 5 3 1]


In [129]:
# last five digits
a="06281717221"
print(a[len(a)-10:])

6281717221


## Multidimensional array

In [132]:
a=n.array([[1,2,3,7],[4,5,6,7],[7,8,9,7],[10,11,12,13]])
a

array([[ 1,  2,  3,  7],
       [ 4,  5,  6,  7],
       [ 7,  8,  9,  7],
       [10, 11, 12, 13]])

In [133]:
a[0:1,0:1]

array([[1]])

In [138]:
a[1:2]

array([[4, 5, 6, 7]])

In [139]:
a[1:2,1:3]

array([[5, 6]])

In [143]:
a[1:2,2:3]

array([[6]])

In [145]:
a[1:3,1:3]
   

array([[5, 6],
       [8, 9]])

In [149]:
a[3:,2:]

array([[12, 13]])

In [151]:
a[0:4:3,0:4:3]

array([[ 1,  7],
       [10, 13]])

In [152]:
a[0:1]

array([[1, 2, 3, 7]])

In [153]:
a

array([[ 1,  2,  3,  7],
       [ 4,  5,  6,  7],
       [ 7,  8,  9,  7],
       [10, 11, 12, 13]])

In [157]:
a[1:4:2,0:4:2]

array([[ 4,  6],
       [10, 12]])

## Strings

In [162]:
a=n.array([["kam","sam","chai"],
          ["uma","kama","mam"]])
a

array([['kam', 'sam', 'chai'],
       ['uma', 'kama', 'mam']], dtype='<U4')

In [163]:
for i in iter(a):
    print(n.char.upper(i))

['KAM' 'SAM' 'CHAI']
['UMA' 'KAMA' 'MAM']


## Linear algebra
### Rank,det,trace,inverse
#### Eigen values,eigenvectors
#### Matrix and vector products

In [169]:
from numpy import linalg as l
a=n.array([[1,2,3],[4,5,6],[6,7,8]])
a
## to find the rank
print(l.matrix_rank(a))
# to find trace of a matrix
print(n.trace(a))
# to find det given matrix
print(l.det(a))
# to find inverse of a given matrix
print(l.inv(a))  # to find power of a matrix
print(l.matrix_power(a,2))

2
14
-1.1657341758564207e-15
[[ 1.7156570e+15 -4.2891425e+15  2.5734855e+15]
 [-3.4313140e+15  8.5782850e+15 -5.1469710e+15]
 [ 1.7156570e+15 -4.2891425e+15  2.5734855e+15]]
[[ 27  33  39]
 [ 60  75  90]
 [ 82 103 124]]


# Matrix Eigen values and Eigen vectors

In [171]:
a=n.array([[1,2j],[5,6j]])
a

array([[1.+0.j, 0.+2.j],
       [5.+0.j, 0.+6.j]])

In [173]:
b,c=l.eigh(a)
print("eigen values are:\n",b)
print("eigen vectors are:\n",c)

eigen values are:
 [-4.52493781  5.52493781]
eigen vectors are:
 [[ 0.67100532+0.j -0.74145253-0.j]
 [-0.74145253+0.j -0.67100532-0.j]]


In [176]:
a=n.diag((1,2,3,4))
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [178]:
b,c=l.eigh(a)
print("eigen values are:\n",b)
print("eigen vectors are:\n",c)

eigen values are:
 [1. 2. 3. 4.]
eigen vectors are:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Matrix and vector products

In [183]:
## dot product
a=64
b=2
print(n.dot(a,b))   # dot product of scalar values
a1=1+2j
b1=2+6j
print(n.dot(a1,b1))

128
(-10+10j)


In [190]:
# to find the dot product of conjugate of vectors
print(n.conjugate((a1,b1)))

[1.-2.j 2.-6.j]


## Pandas

### Data processing And Analysis
### Data-txt,pdf,excel,csv
>1.Accessing rows and coloumns
2.convert the data into csv
3.csv write back to file
4.looping a data
5.adding columns and rows
6.deleting columns and rows
7.display a tablur content
     Data Analysis and preview


### pandas
1-Series object oriented-1-dimensional array
2.Data frame object oriented

In [7]:
import pandas as pd
d=[1,2,3,4,5,6]
d1=["x","y","z"]
x=pd.Series(d1)
y=pd.Series(d)
print(x)
print(y)

0    x
1    y
2    z
dtype: object
0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64


In [ ]:
# Series- Scalar/inter,dictionaries,narray
#DataFrame=dict,list,narray

In [5]:
## Genarate a series object oriented with index by using scalar input
import pandas as pd
d=[1,2,3,4,5,6]
d1=["x","y","z"]
i=["a","b","c"]
x=pd.Series(d1,index=i)
y=pd.Series(d)
print(x)
print(y)

a    x
b    y
c    z
dtype: object
0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64


### Genarate a series object oriented with by using dictionaries

In [35]:
import pandas

In [36]:
dir(pandas)

['Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Float64Index',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int64Index',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NaT',
 'Panel',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseArray',
 'SparseDataFrame',
 'SparseDtype',
 'SparseSeries',
 'TimeGrouper',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt64Index',
 'UInt8Dtype',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_hashtable',
 '_lib',
 '_libs',
 '_np_version_under1p13',
 '_np_version_under1p14',
 '_np_version_under1p15',
 '_np_version_under1p16',
 '_np_version_under1p17

In [14]:
import pandas as pd
di={"name":"kam","ph":"6281717221"}
print(pd.Series(di))

name           kam
ph      6281717221
dtype: object


In [17]:
# n-d-array
import pandas as pd
d=[[1,2,3],[4,5,6]]
print(pd.Series(d,index=[1,2]))

1    [1, 2, 3]
2    [4, 5, 6]
dtype: object


In [21]:
#Data frame object oriented with scalar
import pandas as pd
x=[7,90,56,34,2]
df=pd.DataFrame(x)
df

0
0   7
1  90
2  56
3  34
4   2

In [23]:
import pandas as pd
x=[7,90,56,34,2]
y=[4,2,5,7,8]
c=[3]
df=pd.DataFrame(x,y)
df

0
4   7
2  90
5  56
7  34
8   2

In [24]:
# using Dictionaries
import pandas as pd
x={'x':[1,3,4],'y':[4,5,6],'z':[7,8,9]}
df=pd.DataFrame(x)
print(df)

   x  y  z
0  1  4  7
1  3  5  8
2  4  6  9


In [33]:
import pandas as pd
x=[[1,2,3],[4,5,6],[7,8,9]]
df=pd.DataFrame(x,index=["rank1","rank2","rank3"],columns=["n1","n2","n3"])
print(df)

       n1  n2  n3
rank1   1   2   3
rank2   4   5   6
rank3   7   8   9


### Random values Generation

In [49]:
import pandas as pd
import numpy
df=(numpy.random.rand(2,3))
df
df1=pd.DataFrame(df,columns=['c1','c2','c3'])
df1

c1        c2        c3
0  0.025034  0.677036  0.098341
1  0.850567  0.582140  0.864952

In [50]:
df1.columns ## columns getting

Index(['c1', 'c2', 'c3'], dtype='object')

In [51]:
dir(pandas)

['Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Float64Index',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int64Index',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NaT',
 'Panel',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseArray',
 'SparseDataFrame',
 'SparseDtype',
 'SparseSeries',
 'TimeGrouper',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt64Index',
 'UInt8Dtype',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_hashtable',
 '_lib',
 '_libs',
 '_np_version_under1p13',
 '_np_version_under1p14',
 '_np_version_under1p15',
 '_np_version_under1p16',
 '_np_version_under1p17

In [54]:
# read a csv file
file="income.csv"
import pandas
d=pandas.read_csv(file)
d

GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  62993  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528

In [61]:
df1=pd.DataFrame(d)
df1

GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  62993  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528

In [62]:
df1.columns

Index(['GEOID', 'State', '2005', '2006', '2007', '2008', '2009', '2010',
       '2011', '2012', '2013'],
      dtype='object')

In [67]:
# columns displayed in a format
for i in df1:
    print(i)

GEOID
State
2005
2006
2007
2008
2009
2010
2011
2012
2013


In [68]:
df

GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  62993  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528

In [69]:
df.values

array([['04000US01', 'Alabama', 37150, 37952, 42212, 44476, 39980, 40933,
        42590, 43464, 41381],
       ['04000US02', 'Alaska', 55891, 56418, 62993, 63989, 61604, 57848,
        57431, 63648, 61137],
       ['04000US04', 'Arizona', 45245, 46657, 62993, 46914, 45739, 46896,
        48621, 47044, 50602],
       ['04000US05', 'Arkansas', 36658, 37057, 40795, 39586, 36538,
        38587, 41302, 39018, 39919],
       ['04000US06', 'California', 51755, 55319, 55734, 57014, 56134,
        54283, 53367, 57020, 57528]], dtype=object)

In [73]:
df[["2005"]]

2005
0  37150
1  55891
2  45245
3  36658
4  51755

In [84]:
df1.loc[4]    # 

GEOID     04000US06
State    California
2005          51755
2006          55319
2007          55734
2008          57014
2009          56134
2010          54283
2011          53367
2012          57020
2013          57528
Name: 4, dtype: object

In [91]:
## Accessing elements in
## Row=itertuples(),iterrow(),iteritems()
for i in df.iterrows():
    print(i)

(0, GEOID    04000US01
State      Alabama
2005         37150
2006         37952
2007         42212
2008         44476
2009         39980
2010         40933
2011         42590
2012         43464
2013         41381
Name: 0, dtype: object)
(1, GEOID    04000US02
State       Alaska
2005         55891
2006         56418
2007         62993
2008         63989
2009         61604
2010         57848
2011         57431
2012         63648
2013         61137
Name: 1, dtype: object)
(2, GEOID    04000US04
State      Arizona
2005         45245
2006         46657
2007         62993
2008         46914
2009         45739
2010         46896
2011         48621
2012         47044
2013         50602
Name: 2, dtype: object)
(3, GEOID    04000US05
State     Arkansas
2005         36658
2006         37057
2007         40795
2008         39586
2009         36538
2010         38587
2011         41302
2012         39018
2013         39919
Name: 3, dtype: object)
(4, GEOID     04000US06
State    California
2005    

In [94]:
for i in d.iterrows():
    print(i)


(0, GEOID    04000US01
State      Alabama
2005         37150
2006         37952
2007         42212
2008         44476
2009         39980
2010         40933
2011         42590
2012         43464
2013         41381
Name: 0, dtype: object)
(1, GEOID    04000US02
State       Alaska
2005         55891
2006         56418
2007         62993
2008         63989
2009         61604
2010         57848
2011         57431
2012         63648
2013         61137
Name: 1, dtype: object)
(2, GEOID    04000US04
State      Arizona
2005         45245
2006         46657
2007         62993
2008         46914
2009         45739
2010         46896
2011         48621
2012         47044
2013         50602
Name: 2, dtype: object)
(3, GEOID    04000US05
State     Arkansas
2005         36658
2006         37057
2007         40795
2008         39586
2009         36538
2010         38587
2011         41302
2012         39018
2013         39919
Name: 3, dtype: object)
(4, GEOID     04000US06
State    California
2005    

# Delete and addition of columns and rows
for delete
column-pop,del row-drop

In [107]:
d=pandas.read_csv(file)
d

GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  62993  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528

In [108]:
d.pop("2013")

0    41381
1    61137
2    50602
3    39919
4    57528
Name: 2013, dtype: int64

In [102]:
df.drop(3)

GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  62993  46914  45739  46896  48621   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012  
0  43464  
1  63648  
2  47044  
4  57020

In [109]:
# addition of column
d={"x":1,'y':2}
print(pd.DataFrame(d,index=[1,2]))
new=[1,2,3,4,5,6,7,8,9,10]
d['z']=new
print(pd.DataFrame(d))

   x  y
1  1  2
2  1  2
   x  y   z
0  1  2   1
1  1  2   2
2  1  2   3
3  1  2   4
4  1  2   5
5  1  2   6
6  1  2   7
7  1  2   8
8  1  2   9
9  1  2  10


In [2]:
d={"x":1,'y':2}
print(pd.DataFrame(d,index=[1,2]))
new=[1,2,3,4,5,6,7,8,9,10]
d['z']=new
print(pd.DataFrame(d))

NameError: name 'pd' is not defined